// 7-svelte-kit/src/routes/(account)/account/profile/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import { page } from '$app/stores';

	let { form } = $props();
</script>

<svelte:head>
	<title>Profile</title>
</svelte:head>

<h1 class="text-2xl font-semibold text-zinc-900">Profile</h1>

<section class="mt-8 rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm">
	<h2 class="text-sm font-semibold text-zinc-900">Display name</h2>
	<form class="mt-4 space-y-3" method="POST" action="?/updateProfile" use:enhance>
		<div>
			<label class="text-sm font-medium text-zinc-800" for="name">Name</label>
			<input
				id="name"
				name="name"
				class="mt-1 w-full max-w-md rounded-lg border border-zinc-300 px-3 py-2 text-sm"
				value={$page.data.user?.name ?? ''}
			/>
		</div>
		{#if form?.profileError}
			<p class="text-sm text-red-600">{form.profileError}</p>
		{/if}
		{#if form?.profileOk}
			<p class="text-sm text-emerald-700">Saved.</p>
		{/if}
		<button class="rounded-lg bg-zinc-900 px-4 py-2 text-sm font-semibold text-white" type="submit">
			Save
		</button>
	</form>
</section>

<section class="mt-8 rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm">
	<h2 class="text-sm font-semibold text-zinc-900">Change password</h2>
	<form class="mt-4 space-y-3" method="POST" action="?/changePassword" use:enhance>
		<div>
			<label class="text-sm font-medium text-zinc-800" for="currentPassword">Current password</label>
			<input
				id="currentPassword"
				name="currentPassword"
				type="password"
				autocomplete="current-password"
				class="mt-1 w-full max-w-md rounded-lg border border-zinc-300 px-3 py-2 text-sm"
			/>
		</div>
		<div>
			<label class="text-sm font-medium text-zinc-800" for="newPassword">New password</label>
			<input
				id="newPassword"
				name="newPassword"
				type="password"
				autocomplete="new-password"
				minlength="8"
				class="mt-1 w-full max-w-md rounded-lg border border-zinc-300 px-3 py-2 text-sm"
			/>
		</div>
		{#if form?.passwordError}
			<p class="text-sm text-red-600">{form.passwordError}</p>
		{/if}
		{#if form?.passwordOk}
			<p class="text-sm text-emerald-700">Password updated.</p>
		{/if}
		<button class="rounded-lg bg-zinc-900 px-4 py-2 text-sm font-semibold text-white" type="submit">
			Update password
		</button>
	</form>
</section>

// 4-nuxt-stack/app/pages/account/profile.vue
<script setup lang="ts">
definePageMeta({ middleware: 'auth' })
const { user, refresh } = useAuth()
const name = ref(user.value?.name ?? '')
const passCurrent = ref('')
const passNew = ref('')
const msg = ref('')

async function saveProfile() {
  await $fetch('/api/account/profile', { method: 'PATCH', body: { name: name.value } })
  await refresh()
  msg.value = 'Saved.'
}

async function savePassword() {
  await $fetch('/api/account/password', {
    method: 'POST',
    body: { currentPassword: passCurrent.value, newPassword: passNew.value },
  })
  msg.value = 'Password updated — sign in again.'
}

useSeo({ title: 'Profile' })
</script>

<template>
  <div class="max-w-xl mx-auto px-4 py-16 space-y-10">
    <div>
      <h1 class="text-2xl font-semibold text-white">Profile</h1>
      <form class="mt-4 space-y-3" @submit.prevent="saveProfile">
        <div>
          <label class="text-sm text-slate-400" for="name">Name</label>
          <input id="name" v-model="name" class="mt-1 w-full rounded-md bg-slate-900 border border-slate-700 px-3 py-2" />
        </div>
        <button type="submit" class="px-4 py-2 rounded-lg bg-emerald-500 text-slate-950 text-sm font-medium">Save</button>
      </form>
    </div>
    <div>
      <h2 class="text-lg font-semibold text-white">Change password</h2>
      <form class="mt-4 space-y-3" @submit.prevent="savePassword">
        <input v-model="passCurrent" type="password" placeholder="Current" class="w-full rounded-md bg-slate-900 border border-slate-700 px-3 py-2" />
        <input v-model="passNew" type="password" placeholder="New" class="w-full rounded-md bg-slate-900 border border-slate-700 px-3 py-2" />
        <button type="submit" class="px-4 py-2 rounded-lg border border-slate-700 text-sm">Update password</button>
      </form>
    </div>
    <p v-if="msg" class="text-emerald-400 text-sm">{{ msg }}</p>
  </div>
</template>
