// 8-react-vite-stack/apps/web/src/pages/account/Profile.tsx
import { Helmet } from 'react-helmet-async';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { useApi } from '@/hooks/useApi.js';

const schema = z.object({
  firstName: z.string().max(100).optional(),
  lastName: z.string().max(100).optional(),
});

type Form = z.infer<typeof schema>;

export function ProfilePage() {
  const api = useApi();
  const form = useForm<Form>({ resolver: zodResolver(schema) });

  return (
    <>
      <Helmet>
        <title>Profile — Acme</title>
      </Helmet>
      <h1 className="text-2xl font-semibold">Profile</h1>
      <form
        className="mt-6 max-w-md space-y-4"
        onSubmit={form.handleSubmit(async (values) => {
          await api('/api/me/profile', { method: 'PATCH', body: JSON.stringify(values) });
          alert('Saved');
        })}
      >
        <div>
          <label className="block text-sm font-medium text-slate-700">First name</label>
          <input className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" {...form.register('firstName')} />
        </div>
        <div>
          <label className="block text-sm font-medium text-slate-700">Last name</label>
          <input className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" {...form.register('lastName')} />
        </div>
        <button type="submit" className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white">
          Save
        </button>
      </form>
    </>
  );
}

// 4-nuxt-stack/app/pages/account/profile.vue
<script setup lang="ts">
definePageMeta({ middleware: 'auth' })
const { user, refresh } = useAuth()
const name = ref(user.value?.name ?? '')
const passCurrent = ref('')
const passNew = ref('')
const msg = ref('')

async function saveProfile() {
  await $fetch('/api/account/profile', { method: 'PATCH', body: { name: name.value } })
  await refresh()
  msg.value = 'Saved.'
}

async function savePassword() {
  await $fetch('/api/account/password', {
    method: 'POST',
    body: { currentPassword: passCurrent.value, newPassword: passNew.value },
  })
  msg.value = 'Password updated — sign in again.'
}

useSeo({ title: 'Profile' })
</script>

<template>
  <div class="max-w-xl mx-auto px-4 py-16 space-y-10">
    <div>
      <h1 class="text-2xl font-semibold text-white">Profile</h1>
      <form class="mt-4 space-y-3" @submit.prevent="saveProfile">
        <div>
          <label class="text-sm text-slate-400" for="name">Name</label>
          <input id="name" v-model="name" class="mt-1 w-full rounded-md bg-slate-900 border border-slate-700 px-3 py-2" />
        </div>
        <button type="submit" class="px-4 py-2 rounded-lg bg-emerald-500 text-slate-950 text-sm font-medium">Save</button>
      </form>
    </div>
    <div>
      <h2 class="text-lg font-semibold text-white">Change password</h2>
      <form class="mt-4 space-y-3" @submit.prevent="savePassword">
        <input v-model="passCurrent" type="password" placeholder="Current" class="w-full rounded-md bg-slate-900 border border-slate-700 px-3 py-2" />
        <input v-model="passNew" type="password" placeholder="New" class="w-full rounded-md bg-slate-900 border border-slate-700 px-3 py-2" />
        <button type="submit" class="px-4 py-2 rounded-lg border border-slate-700 text-sm">Update password</button>
      </form>
    </div>
    <p v-if="msg" class="text-emerald-400 text-sm">{{ msg }}</p>
  </div>
</template>
