// 8-react-vite-stack/apps/web/src/pages/account/Subscription.tsx
import { useEffect, useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { useApi } from '@/hooks/useApi.js';

export function SubscriptionPage() {
  const api = useApi();
  const [info, setInfo] = useState<string>('Loading…');

  useEffect(() => {
    void (async () => {
      try {
        const data = await api<{ subscription: { status: string; plan: { name: string } } | null }>(
          '/api/me/subscription'
        );
        if (!data.subscription) setInfo('No active subscription.');
        else setInfo(`${data.subscription.plan.name} — ${data.subscription.status}`);
      } catch {
        setInfo('Unable to load subscription.');
      }
    })();
  }, [api]);

  async function openPortal() {
    const origin = window.location.origin;
    const data = await api<{ url: string }>('/api/me/billing-portal', {
      method: 'POST',
      body: JSON.stringify({ returnUrl: `${origin}/account/subscription` }),
    });
    window.location.href = data.url;
  }

  return (
    <>
      <Helmet>
        <title>Subscription — Acme</title>
      </Helmet>
      <h1 className="text-2xl font-semibold">Subscription</h1>
      <p className="mt-2 text-slate-700">{info}</p>
      <button
        type="button"
        className="mt-6 rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white"
        onClick={() => void openPortal().catch(() => alert('Billing portal unavailable'))}
      >
        Open billing portal
      </button>
    </>
  );
}

// 4-nuxt-stack/app/pages/account/subscription.vue
<script setup lang="ts">
definePageMeta({ middleware: 'auth' })
const { data, refresh } = await useFetch('/api/account/subscription')

async function openPortal() {
  const { url } = await $fetch<{ url: string }>('/api/billing/portal', { method: 'POST' })
  if (url) navigateTo(url, { external: true })
}

useSeo({ title: 'Subscription' })
</script>

<template>
  <div class="max-w-xl mx-auto px-4 py-16">
    <h1 class="text-2xl font-semibold text-white">Subscription</h1>
    <div v-if="data?.subscription" class="mt-6 rounded-lg border border-slate-800 p-4">
      <p class="text-white font-medium">{{ data.subscription.plan.name }}</p>
      <p class="text-sm text-slate-400 mt-1">Status: {{ data.subscription.status }}</p>
      <button type="button" class="mt-4 text-emerald-400 text-sm hover:underline" @click="openPortal">
        Manage billing
      </button>
    </div>
    <p v-else class="mt-6 text-slate-400">
      No active subscription.
      <NuxtLink to="/pricing" class="text-emerald-400">View plans</NuxtLink>
    </p>
  </div>
</template>
