// src/app/admin/orders/page.tsx
import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function AdminOrdersPage() {
  const orders = await prisma.order.findMany({
    orderBy: { createdAt: "desc" },
    take: 100,
    include: { items: true },
  });
  return (
    <div>
      <h1 className="text-2xl font-semibold text-zinc-900 dark:text-zinc-50">Orders</h1>
      <table className="mt-8 w-full text-left text-sm">
        <thead>
          <tr className="border-b border-zinc-200 dark:border-zinc-800">
            <th className="pb-3 font-medium text-zinc-500">ID</th>
            <th className="pb-3 font-medium text-zinc-500">Total</th>
            <th className="pb-3 font-medium text-zinc-500">Status</th>
            <th className="pb-3 font-medium text-zinc-500">When</th>
          </tr>
        </thead>
        <tbody>
          {orders.map((o) => (
            <tr key={o.id} className="border-b border-zinc-100 dark:border-zinc-800/80">
              <td className="py-3 font-mono text-xs">{o.id.slice(0, 12)}…</td>
              <td className="py-3">
                {(o.totalCents / 100).toLocaleString("en-US", { style: "currency", currency: o.currency })}
              </td>
              <td className="py-3">{o.status}</td>
              <td className="py-3 text-zinc-500">{o.createdAt.toLocaleString()}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// 4-nuxt-stack/app/pages/admin/orders.vue
<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: 'admin' })
const { data } = await useFetch('/api/admin/orders')
</script>

<template>
  <div>
    <h1 class="text-2xl font-semibold text-white">Orders</h1>
    <table class="mt-6 w-full text-sm">
      <thead>
        <tr class="text-left text-slate-500 border-b border-slate-800">
          <th class="py-2">ID</th>
          <th class="py-2">Email</th>
          <th class="py-2">Total</th>
          <th class="py-2">Status</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="o in data?.items ?? []" :key="o.id" class="border-b border-slate-800/80">
          <td class="py-3 font-mono text-xs">{{ o.id.slice(0, 8) }}</td>
          <td class="py-3">{{ o.email }}</td>
          <td class="py-3">${{ (o.totalCents / 100).toFixed(2) }}</td>
          <td class="py-3">{{ o.status }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
