// 9-vue-vite-stack/apps/web/src/components/layout/AdminLayout.vue
<script setup lang="ts">
import { RouterLink, RouterView, useRouter } from "vue-router";
import { useAuthStore } from "@/stores/auth";

const auth = useAuthStore();
const router = useRouter();

async function signOut() {
  await auth.logout();
  await router.push("/");
}

const links = [
  { to: "/admin", label: "Dashboard" },
  { to: "/admin/posts", label: "Posts" },
  { to: "/admin/pages", label: "Pages" },
  { to: "/admin/products", label: "Products" },
  { to: "/admin/orders", label: "Orders" },
  { to: "/admin/users", label: "Users" },
  { to: "/admin/forms", label: "Leads" },
  { to: "/admin/media", label: "Media" },
  { to: "/admin/settings", label: "Settings" },
];
</script>

<template>
  <div class="min-h-screen bg-slate-100 text-slate-900">
    <header class="border-b border-slate-200 bg-white">
      <div class="mx-auto flex max-w-7xl items-center justify-between px-4 py-3">
        <RouterLink to="/admin" class="font-semibold">CMS</RouterLink>
        <div class="flex items-center gap-3 text-sm">
          <RouterLink class="text-slate-600 hover:text-slate-900" to="/">View site</RouterLink>
          <button type="button" class="text-slate-600 hover:text-slate-900" @click="signOut">
            Log out
          </button>
        </div>
      </div>
    </header>
    <div class="mx-auto grid max-w-7xl gap-6 px-4 py-8 md:grid-cols-[200px_1fr]">
      <nav class="space-y-1 text-sm">
        <RouterLink
          v-for="l in links"
          :key="l.to"
          :to="l.to"
          class="block rounded-md px-3 py-2 text-slate-600 hover:bg-slate-200/60"
          active-class="bg-slate-200 font-medium text-slate-900"
        >
          {{ l.label }}
        </RouterLink>
      </nav>
      <div class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
        <RouterView />
      </div>
    </div>
  </div>
</template>

// 10-astro-separate/apps/admin/src/pages/AdminLayout.tsx
import { useEffect } from "react";
import { Link, Outlet, useNavigate } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { apiFetch } from "../lib/api";

const links = [
  ["Dashboard", "/admin"],
  ["Posts", "/admin/posts"],
  ["Pages", "/admin/pages"],
  ["Media", "/admin/media"],
  ["Settings", "/admin/settings"],
  ["Search", "/admin/search"],
];

export default function AdminLayout() {
  const nav = useNavigate();
  const gate = useQuery({
    queryKey: ["admin-gate"],
    queryFn: async () => {
      const r = await apiFetch("/v1/admin/dashboard");
      if (r.status === 401) throw new Error("401");
      if (!r.ok) throw new Error("fail");
      return r.json();
    },
    retry: false,
  });

  useEffect(() => {
    if (gate.isError) nav("/login");
  }, [gate.isError, nav]);

  async function logout() {
    await apiFetch("/v1/auth/logout", {
      method: "POST",
      body: JSON.stringify({ scope: "ADMIN" }),
    });
    nav("/login");
  }

  if (gate.isPending) {
    return <div className="p-10 text-sm text-slate-600">Loading admin…</div>;
  }
  if (gate.isError) {
    return null;
  }

  return (
    <div className="grid min-h-screen md:grid-cols-[220px_1fr]">
      <aside className="border-b border-slate-200 bg-white p-4 md:border-b-0 md:border-r">
        <div className="text-sm font-semibold text-slate-900">Nimbus Admin</div>
        <nav className="mt-6 flex flex-col gap-2 text-sm">
          {links.map(([label, href]) => (
            <Link key={href} className="rounded px-2 py-1 text-slate-700 hover:bg-slate-100" to={href}>
              {label}
            </Link>
          ))}
        </nav>
        <button
          className="mt-8 w-full rounded border border-slate-300 px-2 py-1 text-left text-sm text-slate-700 hover:bg-slate-50"
          type="button"
          onClick={() => void logout()}
        >
          Log out
        </button>
      </aside>
      <main className="bg-slate-50 p-6">
        <Outlet />
      </main>
    </div>
  );
}
