// 8-react-vite-stack/apps/web/src/layouts/AccountLayout.tsx
import { NavLink, Outlet } from 'react-router-dom';
import { Container } from '@/components/Container.js';

const linkCls = ({ isActive }: { isActive: boolean }) =>
  `rounded-md px-3 py-2 text-sm font-medium no-underline ${isActive ? 'bg-slate-900 text-white' : 'text-slate-700 hover:bg-slate-100'}`;

export function AccountLayout() {
  return (
    <Container>
      <div className="grid gap-8 md:grid-cols-[220px_1fr]">
        <aside className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
          <p className="px-3 text-xs font-semibold uppercase tracking-wide text-slate-500">Account</p>
          <nav className="mt-3 flex flex-col gap-1">
            <NavLink to="/account" end className={linkCls}>
              Overview
            </NavLink>
            <NavLink to="/account/profile" className={linkCls}>
              Profile
            </NavLink>
            <NavLink to="/account/subscription" className={linkCls}>
              Subscription
            </NavLink>
            <NavLink to="/account/orders" className={linkCls}>
              Orders
            </NavLink>
            <NavLink to="/account/favorites" className={linkCls}>
              Favorites
            </NavLink>
            <NavLink to="/members" className={linkCls}>
              Member library
            </NavLink>
          </nav>
        </aside>
        <section className="min-h-[320px] rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
          <Outlet />
        </section>
      </div>
    </Container>
  );
}

// 3-vue stack/apps/web/src/layouts/AccountLayout.vue
<script setup lang="ts">
import { RouterLink, RouterView, useRouter } from "vue-router";
import { useAuthStore } from "@/stores/auth";

const auth = useAuthStore();
const router = useRouter();

async function signOut() {
  await auth.logout();
  await router.push("/");
}

const links = [
  { to: "/account", label: "Overview" },
  { to: "/account/profile", label: "Profile" },
  { to: "/account/subscription", label: "Subscription" },
  { to: "/account/orders", label: "Orders" },
  { to: "/account/favorites", label: "Favorites" },
];
</script>

<template>
  <div class="min-h-screen bg-slate-100">
    <header class="border-b border-slate-200 bg-white">
      <div class="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-4 py-4">
        <RouterLink to="/" class="font-semibold text-brand-700">Apex Platform</RouterLink>
        <nav class="flex flex-wrap gap-4 text-sm">
          <RouterLink
            v-for="l in links"
            :key="l.to"
            :to="l.to"
            class="text-slate-600 hover:text-brand-600"
            active-class="font-medium text-brand-700"
          >
            {{ l.label }}
          </RouterLink>
          <button type="button" class="text-slate-500 hover:text-brand-600" @click="signOut">Sign out</button>
        </nav>
      </div>
    </header>
    <div class="mx-auto max-w-6xl px-4 py-10">
      <RouterView />
    </div>
  </div>
</template>
