// 7-svelte-kit/src/routes/(account)/account/orders/+page.svelte
<script lang="ts">
	let { data } = $props();
</script>

<svelte:head>
	<title>Orders</title>
</svelte:head>

<h1 class="text-2xl font-semibold text-zinc-900">Orders</h1>
<p class="mt-2 text-sm text-zinc-600">Your purchase history.</p>

<div class="mt-8 overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm">
	<table class="min-w-full divide-y divide-zinc-200 text-sm">
		<thead class="bg-zinc-50 text-left text-xs font-semibold uppercase text-zinc-500">
			<tr>
				<th class="px-4 py-3">Order</th>
				<th class="px-4 py-3">Status</th>
				<th class="px-4 py-3">Total</th>
				<th class="px-4 py-3">Date</th>
			</tr>
		</thead>
		<tbody class="divide-y divide-zinc-100">
			{#if data.orders.length === 0}
				<tr>
					<td class="px-4 py-6 text-zinc-600" colspan="4">No orders yet.</td>
				</tr>
			{:else}
				{#each data.orders as o (o.id)}
					<tr>
						<td class="px-4 py-3 font-mono text-xs text-zinc-800">{o.id}</td>
						<td class="px-4 py-3 capitalize text-zinc-700">{o.status}</td>
						<td class="px-4 py-3 text-zinc-800">
							{(o.totalCents / 100).toFixed(2)}
							{o.currency.toUpperCase()}
						</td>
						<td class="px-4 py-3 text-zinc-600">{o.createdAt.toLocaleString()}</td>
					</tr>
				{/each}
			{/if}
		</tbody>
	</table>
</div>

// react-stack/src/app/(admin)/admin/orders/page.tsx
import { prisma } from "@/lib/db";

export default async function AdminOrdersPage() {
  const orders = await prisma.order.findMany({
    orderBy: { createdAt: "desc" },
    take: 50,
    include: { items: true },
  });
  return (
    <div>
      <h1 className="text-2xl font-semibold tracking-tight">Orders</h1>
      <div className="mt-8 overflow-x-auto rounded-xl border">
        <table className="w-full text-left text-sm">
          <thead className="bg-muted/50 text-xs uppercase text-muted-foreground">
            <tr>
              <th className="px-4 py-3">Date</th>
              <th className="px-4 py-3">Email</th>
              <th className="px-4 py-3">Total</th>
              <th className="px-4 py-3">Status</th>
            </tr>
          </thead>
          <tbody>
            {orders.map((o) => (
              <tr key={o.id} className="border-t">
                <td className="px-4 py-3">{o.createdAt.toLocaleString()}</td>
                <td className="px-4 py-3">{o.email}</td>
                <td className="px-4 py-3">
                  ${(o.totalCents / 100).toFixed(2)}
                </td>
                <td className="px-4 py-3">{o.status}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
