// src/components/layout/site-header.tsx
import Link from "next/link";
import { SiteHeaderAuth } from "@/components/layout/site-header-auth";

const nav = [
  { href: "/about", label: "About" },
  { href: "/services", label: "Services" },
  { href: "/pricing", label: "Pricing" },
  { href: "/blog", label: "Blog" },
  { href: "/contact", label: "Contact" },
];

export function SiteHeader() {
  return (
    <header className="border-b border-zinc-200/80 bg-white/80 backdrop-blur dark:border-zinc-800 dark:bg-zinc-950/80">
      <div className="mx-auto flex h-16 max-w-6xl items-center justify-between gap-4 px-4 sm:px-6">
        <Link href="/" className="text-lg font-semibold tracking-tight text-zinc-900 dark:text-zinc-50">
          Platform
        </Link>
        <nav className="hidden items-center gap-6 md:flex" aria-label="Main">
          {nav.map((item) => (
            <Link
              key={item.href}
              href={item.href}
              className="text-sm font-medium text-zinc-600 transition hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-100"
            >
              {item.label}
            </Link>
          ))}
          <Link
            href="/search"
            className="text-sm font-medium text-zinc-600 transition hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-100"
          >
            Search
          </Link>
        </nav>
        <div className="flex items-center gap-3">
          <SiteHeaderAuth />
        </div>
      </div>
    </header>
  );
}

// 9-vue-vite-stack/apps/web/src/components/layout/SiteHeader.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { RouterLink, useRoute } from "vue-router";
import { api } from "@/lib/api";
import { useAuthStore } from "@/stores/auth";

const auth = useAuthStore();
const route = useRoute();
const items = ref<{ label: string; href: string }[]>([]);

onMounted(async () => {
  try {
    const r = await api<{ items: { label: string; href: string }[] }>("/api/v1/public/nav/header");
    items.value = r.items ?? [];
  } catch {
    items.value = [
      { label: "Home", href: "/" },
      { label: "About", href: "/about" },
      { label: "Services", href: "/services" },
      { label: "Pricing", href: "/pricing" },
      { label: "Blog", href: "/blog" },
      { label: "Contact", href: "/contact" },
    ];
  }
});

function isActive(href: string) {
  if (href === "/") return route.path === "/";
  return route.path.startsWith(href);
}
</script>

<template>
  <header class="border-b border-white/10 bg-brand-900/80 backdrop-blur">
    <div class="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-4">
      <RouterLink to="/" class="text-lg font-semibold tracking-tight text-white">
        Apex Platform
      </RouterLink>
      <nav class="hidden items-center gap-1 md:flex" aria-label="Primary">
        <RouterLink
          v-for="it in items"
          :key="it.href"
          :to="it.href"
          class="rounded-md px-3 py-2 text-sm font-medium text-slate-200 hover:bg-white/5 hover:text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-accent-400"
          :class="isActive(it.href) ? 'bg-white/10 text-white' : ''"
        >
          {{ it.label }}
        </RouterLink>
      </nav>
      <div class="flex items-center gap-2">
        <RouterLink
          v-if="auth.isAuthed && auth.me?.permissions?.includes('posts.read')"
          to="/admin"
          class="rounded-md px-3 py-2 text-sm text-accent-400 hover:bg-white/5"
        >
          Admin
        </RouterLink>
        <RouterLink
          v-if="auth.isAuthed"
          to="/account"
          class="rounded-md px-3 py-2 text-sm text-slate-200 hover:bg-white/5"
        >
          Account
        </RouterLink>
        <RouterLink
          v-else
          to="/login"
          class="rounded-md bg-accent-500 px-3 py-2 text-sm font-medium text-brand-950 hover:bg-accent-400"
        >
          Log in
        </RouterLink>
      </div>
    </div>
  </header>
</template>
