// 7-svelte-kit/src/routes/(marketing)/search/+page.svelte
<script lang="ts">
	let { data } = $props();
</script>

<svelte:head>
	<title>Search</title>
</svelte:head>

<h1 class="text-2xl font-semibold text-zinc-900">Search</h1>

<form class="mt-6 flex gap-2" method="get" action="/search">
	<label class="sr-only" for="q">Query</label>
	<input
		id="q"
		name="q"
		class="w-full max-w-md rounded-lg border border-zinc-300 px-3 py-2 text-sm"
		placeholder="Search posts, pages, products…"
		value={data.q}
	/>
	<button class="rounded-lg bg-zinc-900 px-4 py-2 text-sm font-semibold text-white" type="submit">
		Search
	</button>
</form>

<ul class="mt-8 space-y-4">
	{#each data.results as r (`${r.type}-${r.id}`)}
		<li class="rounded-xl border border-zinc-200 bg-white p-4 shadow-sm">
			<p class="text-xs font-medium uppercase text-zinc-500">{r.type}</p>
			<a class="mt-1 block font-semibold text-zinc-900 hover:text-indigo-600" href={r.href}>
				{r.title}
			</a>
			{#if r.snippet}
				<p class="mt-1 text-sm text-zinc-600">{r.snippet}</p>
			{/if}
		</li>
	{:else}
		{#if data.q.length >= 2}
			<li class="text-sm text-zinc-600">No results.</li>
		{:else}
			<li class="text-sm text-zinc-600">Enter at least 2 characters.</li>
		{/if}
	{/each}
</ul>

// react-stack/src/app/(marketing)/search/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { siteSearch } from "@/lib/search";

export const metadata: Metadata = {
  title: "Search",
};

export default async function SearchPage({
  searchParams,
}: {
  searchParams: Promise<{ q?: string }>;
}) {
  const { q } = await searchParams;
  const results = await siteSearch(q ?? "");

  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6">
      <h1 className="text-3xl font-semibold tracking-tight">Search</h1>
      <form className="mt-8 flex gap-2" action="/search" method="get">
        <input
          name="q"
          defaultValue={q}
          placeholder="Search posts, products, authors, pages…"
          className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
          aria-label="Search query"
        />
        <button
          type="submit"
          className="inline-flex h-10 items-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground"
        >
          Search
        </button>
      </form>
      <ul className="mt-10 space-y-4">
        {results.map((r) => (
          <li key={`${r.type}-${r.id}`}>
            <p className="text-xs uppercase text-muted-foreground">{r.type}</p>
            <Link href={r.href} className="font-medium hover:underline">
              {r.title}
            </Link>
            <p className="text-sm text-muted-foreground">{r.excerpt}</p>
          </li>
        ))}
        {q && !results.length ? (
          <li className="text-sm text-muted-foreground">No results.</li>
        ) : null}
      </ul>
    </div>
  );
}
