// 5-angular-stack/apps/web/src/app/public/not-found/not-found.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-not-found',
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="flex min-h-[50vh] flex-col items-center justify-center px-4 text-center">
      <h1 class="text-4xl font-bold text-slate-800">404</h1>
      <p class="mt-2 text-slate-600">This page could not be found.</p>
      <a routerLink="/" class="mt-6 font-medium text-brand-600 hover:underline">Back home</a>
    </div>
  `,
})
export class NotFoundComponent {}

// react-stack/src/app/not-found.tsx
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function NotFound() {
  return (
    <div className="mx-auto flex min-h-[60vh] max-w-lg flex-col items-center justify-center gap-6 px-4 text-center">
      <p className="text-sm font-medium text-muted-foreground">404</p>
      <h1 className="text-3xl font-semibold tracking-tight">Page not found</h1>
      <p className="text-muted-foreground">
        The page you are looking for does not exist or was moved.
      </p>
      <Button asChild>
        <Link href="/">Back home</Link>
      </Button>
    </div>
  );
}
