// 8-react-vite-stack/apps/web/src/pages/Checkout.tsx
import { useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { useAppAuth } from '@/auth/app-auth-context.js';
import { Container } from '@/components/Container.js';
import { apiFetch } from '@/lib/api.js';

export function CheckoutPage() {
  const { isSignedIn, getToken } = useAppAuth();
  const [email, setEmail] = useState('');
  const [error, setError] = useState<string | null>(null);

  async function pay() {
    setError(null);
    try {
      const token = isSignedIn ? await getToken() : null;
      const origin = window.location.origin;
      const data = await apiFetch<{ url: string | null }>('/api/checkout/session', {
        method: 'POST',
        body: JSON.stringify({
          successUrl: `${origin}/thank-you?type=checkout`,
          cancelUrl: `${origin}/cart`,
          guestEmail: isSignedIn ? undefined : email || undefined,
        }),
        token,
      });
      if (data.url) window.location.href = data.url;
      else setError('Stripe Checkout URL missing.');
    } catch (e: unknown) {
      const msg = typeof e === 'object' && e && 'error' in e ? String((e as { error: string }).error) : 'Checkout failed';
      setError(msg);
    }
  }

  return (
    <>
      <Helmet>
        <title>Checkout — Acme Store</title>
      </Helmet>
      <Container>
        <h1 className="text-3xl font-semibold">Checkout</h1>
        {!isSignedIn && (
          <div className="mt-4 max-w-md">
            <label className="block text-sm font-medium text-slate-700" htmlFor="guest-email">
              Email (guest checkout)
            </label>
            <input
              id="guest-email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2"
            />
          </div>
        )}
        {error && <p className="mt-4 text-sm text-red-700">{error}</p>}
        <button
          type="button"
          className="mt-6 rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white"
          onClick={() => void pay()}
        >
          Pay with Stripe
        </button>
      </Container>
    </>
  );
}

// 4-nuxt-stack/app/pages/checkout.vue
<script setup lang="ts">
const cart = useCartStore()
const { user } = useAuth()
const email = ref(user.value?.email ?? '')
const error = ref('')
const loading = ref(false)

useSeo({ title: 'Checkout' })

async function pay() {
  if (!cart.lines.length) return
  loading.value = true
  error.value = ''
  try {
    const { url } = await $fetch<{ url: string | null }>('/api/checkout/create', {
      method: 'POST',
      body: {
        items: cart.lines.map((l) => ({ productId: l.productId, quantity: l.quantity })),
        email: email.value || undefined,
      },
    })
    if (url) {
      cart.clear()
      navigateTo(url, { external: true })
    }
  } catch (e: unknown) {
    error.value = e instanceof Error ? e.message : 'Checkout failed'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="max-w-lg mx-auto px-4 py-16">
    <h1 class="text-3xl font-semibold text-white">Checkout</h1>
    <p class="mt-4 text-slate-400 text-sm">Secure payment via Stripe Checkout.</p>
    <div v-if="!user" class="mt-6">
      <label for="email" class="block text-sm text-slate-400">Email</label>
      <input
        id="email"
        v-model="email"
        type="email"
        required
        class="mt-1 w-full rounded-md bg-slate-900 border border-slate-700 px-3 py-2"
      />
    </div>
    <p v-if="error" class="mt-4 text-red-400 text-sm">{{ error }}</p>
    <button
      type="button"
      class="mt-8 w-full py-3 rounded-lg bg-emerald-500 text-slate-950 font-semibold disabled:opacity-50"
      :disabled="loading || !cart.lines.length"
      @click="pay"
    >
      {{ loading ? 'Redirecting…' : 'Pay with Stripe' }}
    </button>
  </div>
</template>
